### ISSUE TITLE
字体找不到,乱码

### ISSUE THREAD

**Issue by liushuangxi** [big-pang/laravel5.2-Admin#9]
![qq 20161108175236](https://cloud.githubusercontent.com/assets/5173262/20094452/2e0704de-a5dc-11e6-94d8-d631382ee2b2.png)
目录大小写的问题确实是有的，之前windows开发， 没注意。 你的字体的问题我没办法重现， 字体是在bootstrap（public/bootstrap/fonts）里，你检查下

**Comment by liushuangxi** [comment]
本地字体文件,没有配置nginx

**Comment by big-pang** [comment]
呵呵，呵呵。你看下资源是哪里加载错误

**Comment by liushuangxi** [comment]
1.字体,JS,CSS需要配置nginx支持(本地已配置可用)
2.目录大小写问题

**Comment by liushuangxi** [comment]
![qq 20161109181045](https://cloud.githubusercontent.com/assets/5173262/20134851/f14fda62-a6a7-11e6-84eb-a7eeabfe9fab.png)

**Comment by big-pang** [comment]
目录大小写的问题确实是有的，之前windows开发， 没注意。  你的字体的问题我没办法重现， 字体是在bootstrap（public/bootstrap/fonts）里
